runtime: custom
env: flex
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
network:
  forwarded_ports:
    - 2222:8090
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300